apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slack_bot.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  GITHUB_TOKEN: {{ .Values.github.token | b64enc }}
  SLACK_BOT_TOKEN: {{ .Values.slack.botToken | b64enc }}
  SLACK_APP_TOKEN: {{ .Values.slack.appToken | b64enc }}
  SENTRY_DSN: {{ .Values.sentry.dsn | b64enc }}
  YOUTRACK_API_TOKEN: {{ .Values.youtrack.token | b64enc }}
